# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Zero Hour Sleep
subtitle:
email: charbel_hanna@hotmail.com
description: >- # this means to ignore newlines until "baseurl:"
  open your eyes!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Charbelh
github_username:  charbelhanna
logo: "/assets/images/zhs-bigger.jpg"
masthead_title: "Open your eyes!"
search: true

# twitter cards
twitter:
  username: zerohoursleep

#include social profile in search
social:
  type:  Person # Person or Organization (defaults to Person)
  name:  Charel HANNA # If the user or organization name differs from the site's name
  links:
    - "https://www.linkedin.com/in/hannacharbel/"
    - "https://twitter.com/charbelh"
    - "https://www.instagram/charbekhanna"  
    - "https://www.facebook.com/charbel.hanna1"

#Comments system settings
repository: # GitHub username/repo-name e.g. "charbelhanna/charbelhanna.github.io"
comments:
  provider: "utterances"
  utterances:
    theme: "github-light" # "github-dark"
    issue-term: "pathname" 
    label: "comment"  

# footer links

footer:
  links:
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"  # fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/hannacharbel/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/charbelh"
    - label: "Github"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/charbelhanna"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram/charbekhanna"
    
# Build settings

# theme settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji 

# set post defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_date: true
      read_time: true
      comments: true
      author_profile: true
      related: true
      shared: true
 # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      header: 
        overlay_image: /assets/images/8.jpg  



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
